news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('<int:post_id>/comments/', include('comments.urls')),
    path('one_time_codes/', include('one_time_codes.urls')),
    path('', include('posts.urls')),
]

news_project/posts/urls.py
from django.urls import path, include
from .views import AddPostView, PostListView, PostDetailView

app_name = 'posts'
urlpatterns = [
    path('add/', AddPostView.as_view(), name='add'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
]

news_project/users/urls.py
from django.urls import path
from users.views import UserRegistrationView, UserLoginView, UserLogoutView

app_name = 'users'
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

news_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from one_time_codes.models import OneTimeCode


class UserProfile(models.Model):
    GROUPS = (
        ('U', 'User'),
        ('A', 'Admin'),
        ('E', 'Editor'),
    )
    first_name = models.CharField(max_length=50, null=True, blank=True)
    surname = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile',
    )
    group = models.CharField(max_length=1, choices=GROUPS, default='U')

    @property
    def email_confirmed(self):
        return bool(OneTimeCode.objects.filter(user=self.user, is_confirmed=True))

    def __str__(self):
        return f'profile of user {self.user.username}'

news_project/mainpage/views.py
from django.shortcuts import render

# Create your views here.

news_project/mainpage/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %} default title {% endblock %}</title>
    {% block head %}
    {%  endblock %}
  </head>
  <body>
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="container">
        {% if user.is_authenticated %}
            <p>Hello, {{ user.username }}</p>
            <p>Your status is {{ user.profile.get_group_display }}</p>
            <p><a href="{% url 'users:logout' %}">Logout</a></p>
        {% else %}
            <p>Hello, guest.</p>
            <p><a href="{% url 'users:login' %}">Login</a></p>
            <p><a href="{% url 'users:registration' %}">Registration</a></p>
        {% endif %}
        <p><a href="{% url 'posts:list' %}">Main page</a></p>
    </div>
     {% block body %}
      default content
     {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.slim.min.js' %}" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>