news_project/comments/urls.py
from django.urls import path
from .views import AddCommentView, CommentListView

app_name = 'comments'
urlpatterns = [
    path('add/', AddCommentView.as_view(), name='add'),
    path('', CommentListView.as_view(), name='list'),
]

news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('<int:post_id>/comments/', include('comments.urls')),
    path('one_time_codes/', include('one_time_codes.urls')),
    path('', include('posts.urls')),
]

news_project/posts/urls.py
from django.urls import path, include
from .views import AddPostView, PostListView, PostDetailView

app_name = 'posts'
urlpatterns = [
    path('add/', AddPostView.as_view(), name='add'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
]

news_project/comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post


class Comment(models.Model):

    body = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )

    def __str__(self):
        return f'Comment by {self.author.username} in post {self.post.title}, {self.date}'

news_project/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Comment
        fields = ['body',]

news_project/comments/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.views.generic import View, ListView
from .forms import CommentForm
from .models import Comment
from posts.models import Post
from users.models import UserProfile
from django.conf import settings
from mailer.sender import send_mail


class AddCommentView(View):
    def get(self, request, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        template_name = 'add_comment.html'
        args = {'comment_form': CommentForm()}
        return render(request, template_name, context=args)

    def post(self, request, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        template_name = 'add_comment.html'
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = get_object_or_404(
                Post,
                pk=kwargs.get('post_id', -1)
            )
            new_comment.author = request.user
            if UserProfile.objects.get(user=new_comment.post.author).email_confirmed:
                comments_link = request.build_absolute_uri(
                    reverse('comments:list',
                            kwargs={'post_id': new_comment.post.pk}))
                html_content = f'You have got a new comment by {new_comment.author.username}:<br>' + \
                               f'{new_comment.body}<br>' + \
                               'Go to comments: <br>' + \
                               f'<a href="{comments_link}">{comments_link}</a>'
                send_mail.delay(from_email=settings.SENDGRID_SENDERS_EMAIL,
                          to_emails=new_comment.post.author.email,
                          subject='New comment notification',
                          html_content=html_content)
            new_comment.save()
            messages.add_message(request, messages.INFO, 'Your comment added')
            return redirect(reverse('posts:detail', args=[kwargs.get('post_id'),]))
        return render(request, template_name, context={'comment_form': comment_form})


class CommentListView(ListView):

    model = Comment
    paginate_by = 10
    template_name = 'comment_list.html'

    def get_queryset(self):
        post = get_object_or_404(
                Post,
                pk=self.kwargs.get('post_id', -1)
            )
        return Comment.objects.filter(post=post).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        args = {'post_id': self.kwargs.get('post_id', -1)}
        context.update(args)
        return context

news_project/comments/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}
  Add comment
{% endblock %}

{% block body %}
    <div class="container">
      <h1>Add Comment</h1>
    </div>
    <div class="container">
        <form method='POST'>
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="Add">
        </form>
    </div>
{% endblock %}

news_project/comments/templates/comment_list.html
{% extends 'base.html' %}
{% block title %}
    Comment List
{% endblock %}

{% block body %}
    <div class="container">
      <h3>Comments</h3>
    </div>
    <div class="container">
        <p><a href="{% url 'posts:detail' pk=post_id %}">Back to post</a></p>
        <div class="container">
            <ul  class="list-group">
                {% for comment in object_list %}
                    <li class="list-group-item">
                        <p>
                            {{ comment.body }}
                        </p>
                        <p>
                            <i>{{ comment.author.username }}, {{ comment.date }}</i>
                        </p>
                    </li>
                {% empty %}
                    <li class="list-group-item">No comments yet.</li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <div class="container">
            {% if is_paginated %}
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                {% endif %}
              </ul>
            {% endif %}
        </div>

        <div class="container">
            <p>
                {% if user.is_authenticated %}
                  <a href="{% url 'comments:add' post_id=post_id %}">Add Comment</a>
                {% else %}
                    Login to comment
                {% endif %}
            </p>
        </div>

    </div>
{% endblock %}