news_project/comments/urls.py
from django.urls import path
from .views import AddCommentView, CommentListView

app_name = 'comments'
urlpatterns = [
    path('add/', AddCommentView.as_view(), name='add'),
    path('', CommentListView.as_view(), name='list'),
]

news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('<int:post_id>/comments/', include('comments.urls')),
    path('one_time_codes/', include('one_time_codes.urls')),
    path('', include('posts.urls')),
]

news_project/posts/urls.py
from django.urls import path, include
from .views import AddPostView, PostListView, PostDetailView

app_name = 'posts'
urlpatterns = [
    path('add/', AddPostView.as_view(), name='add'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
]

news_project/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField


class Post(models.Model):
    STATUSES = (
        ('P', 'Pending'),
        ('A', 'Approved'),
        ('D', 'Declined'),
    )
    title = models.CharField(max_length=500)
    body = HTMLField()
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    status = models.CharField(max_length=1, choices=STATUSES, default='P')

    def __str__(self):
        return f'{self.title} by {self.author.username}'

news_project/posts/forms.py
from django import forms
from .models import Post
# from django.contrib.flatpages.models import FlatPage
from tinymce.widgets import TinyMCE


class PostForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Post
        fields = ['title', 'body']

news_project/posts/views.py
from django.shortcuts import render, redirect, reverse
from django.core.exceptions import PermissionDenied
from django.views.generic import View, ListView, DetailView
from .forms import PostForm
from users.models import UserProfile
from django.contrib import messages
from .models import Post


class AddPostView(View):
    def get(self, request, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        template_name = 'add_post.html'
        args = {'post_form': PostForm()}
        return render(request, template_name, context=args)

    def post(self, request, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        template_name = 'add_post.html'
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = request.user
            if UserProfile.objects.get(user=request.user).group in ['A', 'E']:
                new_post.status = 'A'
                status_label = 'published'
            else:
                new_post.status = 'P'
                status_label = 'is pending'
            new_post.save()
            messages.add_message(request, messages.INFO, f'Your post {status_label}')
            return redirect(reverse('posts:list'))
        return render(request, template_name, context={'post_form': post_form})


class PostListView(ListView):

    model = Post
    paginate_by = 10
    template_name = 'post_list.html'

    def get_queryset(self):
        return Post.objects.filter(status='A').order_by('-date')


class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'

news_project/posts/templates/add_post.html
{% extends 'base.html' %}
{% block head %}
    {{ post_form.media }}
{%  endblock %}

{% block title %}
  Add post
{% endblock %}

{% block body %}
    <div class="container">
      <h1>Add Post</h1>
    </div>
    <div class="container">
        <form method='POST'>
            {% csrf_token %}
            {{ post_form.as_p }}
            <input type="submit" value="Add">
        </form>
    </div>
{% endblock %}

news_project/posts/templates/post.html
{% extends 'base.html' %}
{% block title %}
  {{ object.title }}
{% endblock %}

{% block body %}
    <div class="container">
      <h1>{{ object.title }}</h1>
    </div>
    <div class="container">
        <p><i>by {{ object.author.username }}, {{ object.date }}</i></p>
    </div>
    <div class="container">
        {{ object.body|safe }}
    </div>
    <div class="container">
        <p><a href="{% url 'comments:list' post_id=object.pk %}">Comments</a></p>
    </div>
{% endblock %}

news_project/posts/templates/post_list.html
{% extends 'base.html' %}
{% block title %}
    Post List
{% endblock %}

{% block body %}
    <div class="container">
      <h1>News List</h1>
    </div>
    <div class="container">
        <div class="container">
            <ul class="list-group">
                {% for post in object_list %}
                    <li class="list-group-item"><b><a href="{% url 'posts:detail' pk=post.pk %}"> {{ post.title }}</a></b> by {{ post.author.username }}, {{ post.date }}</li>
                {% empty %}
                    <li class="list-group-item">No posts yet.</li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <div class="container">
            {% if is_paginated %}
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                {% endif %}
              </ul>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <p>
            {% if user.is_authenticated %}
              <a href="{% url 'posts:add' %}">Add Post</a>
            {% else %}
                Login to post
            {% endif %}
        </p>
    </div>
{% endblock %}